import "./globals.css";

export const metadata = {
  title: "ALLEN LABRAGUE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/assets/metaverse-people.png" />
      </head>
      <body>{children}</body>
    </html>
  );
}
