import "./globals.css";
import { Providers } from "./providers";

export const metadata = {
  title: "ALLEN LABRAGUE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className="dark:bg-[#121212]">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
